services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: canaco
      POSTGRES_USER: hower
      POSTGRES_PASSWORD: 1234
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
